<%
'-----------------------------------------------
'		 QUIZ MASTER
'
'
'	 Copyright (c) to Deepak Sharma
'
'	
'      Constants include file for VBScript
'
'-----------------------------------------------


'---- OptionTypeEnum Values ----

Const Options1 = 1
Const Options2 = 2
Const Options3 = 3
Const Options4 = 4


'---- ResultTypeEnum Values ----

Const Marks = 1
Const Comments = 2
Const Remarks = 3


'---- Correct_AnswerTypeEnum Values ----

Const Status = 1
Const UserOption = 2
Const CorrectOption = 3
Const Increment = 4


'---- FactTypeEnum Values ----

Const Maximum = 1
Const Minimum = 2
Const Average = 3
Const TotalQuestion = 4
Const CorrectAnswers = 5
Const WrongAnswers = 6

%>
